### successfully create a carpark
POST http://localhost:8800/api/carparks
Content-Type: application/json

{
    "carpark_name": "Joe carpark",
    "adress": "296 Queen St, Melbourne",
    "location": "[-37.811758, 144.959334]",
    "price": "Daily from $5",
    "rating": 2
}

### successfully register a user
POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "username": "user1",
    "email": "user1@test.com",
    "password": "password1"
}

### successfully register a user and password has been encrypted 
POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "username": "user2",
    "email": "user2@test.com",
    "password": "password2"
}

### successfully signin as a user
POST http://localhost:8800/api/auth/login
Content-Type: application/json

{
    "username": "user2updated",
    "password": "password2"
}

### successfully update a username
PUT http://localhost:8800/api/users/6361bc6fad04d4c042b5e3ef
Content-Type: application/json

{
    "username": "user2updated",
}

### successfully verify a user
GET http://localhost:8800/api/users/checkuser/6361bc6fad04d4c042b5e3ef
Content-Type: application/json

{
    "username": "user2updated",
}
// => "hello user, you are loged in and you can delete your acount."


### successfully create a booking
POST http://localhost:8800/api/bookings
Content-Type: application/json

{
    "username": "user2updated",
    "carpark_name": "Joe carpark",
    "booking_date": "2020-01-11T18:00:01"
}
